### ISSUE TITLE
LLVM can't find

### ISSUE THREAD

**Issue by mrLSD** [KyleMayes/install-llvm-action#5]
My actions config:
https://github.com/mrLSD/iLang/blob/master/.github/workflows/ci.yml

Log for LLVM installation:
```
Run KyleMayes/install-llvm-action@v1
Installing LLVM and Clang 11.0 (11.0.0)...
Downloading and extracting 'https://github.com/llvm/llvm-project/releases/download/llvmorg-11.0.0/clang+llvm-11.0.0-x86_64-linux-gnu-ubuntu-20.04.tar.xz'...
/bin/tar xf /home/runner/work/_temp/c3cdae7f-fb35-410b-a8d7-cc42c1b4d936 -C /home/runner/work/_temp/llvm --strip-components=1
Installed LLVM and Clang 11.0 (11.0.0)!
```

Error from my action:
```
   Compiling nom_locate v2.1.0
error: failed to run custom build command for `llvm-sys v110.0.0`

Caused by:
  process didn't exit successfully: `/home/runner/work/iLang/iLang/target/debug/build/llvm-sys-ec220cd82f32c16e/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=LLVM_SYS_110_PREFIX
  cargo:rerun-if-env-changed=LLVM_SYS_110_IGNORE_BLACKLIST
  cargo:rerun-if-env-changed=LLVM_SYS_110_STRICT_VERSIONING
  cargo:rerun-if-env-changed=LLVM_SYS_110_NO_CLEAN_CFLAGS
  cargo:rerun-if-env-changed=LLVM_SYS_110_USE_DEBUG_MSVCRT
  cargo:rerun-if-env-changed=LLVM_SYS_110_FFI_WORKAROUND

  --- stderr
  thread 'main' panicked at 'Could not determine LLVM version from llvm-config.', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/llvm-sys-110.0.0/build.rs:219:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: Process completed with exit code 101.

```

Do you have some ideas how to fix it?

**Comment by mrLSD** [comment]
Specifically LLVM 11 not supported

**Comment by aminya** [comment]
I have tested this action will LLVM 10, 11, 12 with no issues.

**Comment by mrLSD** [comment]
@aminya I tested again.
It works only for `ubuntu20.04` actions.
For `ubuntu18.04 ` - partly (can't build for `rust nighlty`)
For `ubuntu16.04` - completely not working.

**Action**:
https://github.com/mrLSD/iLang/runs/2731433970?check_suite_focus=true

**Log**:
```
2021-06-02T20:28:00.5519714Z    Compiling nom_locate v2.1.0
2021-06-02T20:28:00.7980365Z error: failed to run custom build command for `llvm-sys v110.0.1`
2021-06-02T20:28:00.7981297Z 
2021-06-02T20:28:00.7981881Z Caused by:
2021-06-02T20:28:00.7983488Z   process didn't exit successfully: `/home/runner/work/iLang/iLang/target/debug/build/llvm-sys-7434f1645de99489/build-script-build` (exit code: 101)
2021-06-02T20:28:00.7984905Z   --- stdout
2021-06-02T20:28:00.7985958Z   cargo:rerun-if-env-changed=LLVM_SYS_110_PREFIX
2021-06-02T20:28:00.7987279Z   cargo:rerun-if-env-changed=LLVM_SYS_110_IGNORE_BLACKLIST
2021-06-02T20:28:00.7988592Z   cargo:rerun-if-env-changed=LLVM_SYS_110_STRICT_VERSIONING
2021-06-02T20:28:00.7989893Z   cargo:rerun-if-env-changed=LLVM_SYS_110_NO_CLEAN_CFLAGS
2021-06-02T20:28:00.7991167Z   cargo:rerun-if-env-changed=LLVM_SYS_110_USE_DEBUG_MSVCRT
2021-06-02T20:28:00.7992462Z   cargo:rerun-if-env-changed=LLVM_SYS_110_FFI_WORKAROUND
2021-06-02T20:28:00.7993166Z 
2021-06-02T20:28:00.7993891Z   --- stderr
2021-06-02T20:28:00.7995604Z   thread 'main' panicked at 'Could not determine LLVM version from llvm-config.', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/llvm-sys-110.0.1/build.rs:215:10
2021-06-02T20:28:00.7997282Z   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2021-06-02T20:28:00.7998248Z warning: build failed, waiting for other jobs to finish...
2021-06-02T20:28:01.6995910Z error: build failed
2021-06-02T20:28:01.7028671Z ##[error]Process completed with exit code 101.
2021-06-02T20:28:01.7146483Z Post job cleanup.
2021-06-02T20:28:01.8340039Z [command]/usr/bin/git version
2021-06-02T20:28:01.8400418Z git version 2.31.1
2021-06-02T20:28:01.8441590Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2021-06-02T20:28:01.8489661Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2021-06-02T20:28:01.8725302Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2021-06-02T20:28:01.8771126Z http.https://github.com/.extraheader
2021-06-02T20:28:01.8773134Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2021-06-02T20:28:01.8811014Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2021-06-02T20:28:01.9163645Z Cleaning up orphan processes
```

**Comment by aminya** [comment]
That's because `llvm-sys` doesn't properly use `llvm-config` to find the version of LLVM. There is no issue with this action. Please close this and open an issue in the respective repository:
https://gitlab.com/taricorp/llvm-sys.rs

**Comment by aminya** [comment]
Oh, you are still using `v1`. Please change it to `master`.
https://github.com/mrLSD/iLang/actions/runs/900622163/workflow#L36

@KyleMayes should update the v1 tag.

**Comment by mrLSD** [comment]
It was not related to `llvm-sys`. I just updated to `master` and my issue was fixed.

@aminya any ideas about how to fix it for `windows-latest` os target?

**Comment by aminya** [comment]
Windows already works without any issues.

**Comment by mrLSD** [comment]
@aminya I wouldn't ask if it worked

https://github.com/mrLSD/iLang/commit/e98f44f71d7e65332cfb85d486ef5987a914a9d5

**Comment by aminya** [comment]
What's the error message?
