### ISSUE TITLE
Support LLVM 18

### ISSUE THREAD

**Issue by Sedeniono** [KyleMayes/install-llvm-action#63]
Attempting to use clang 18, I got these error messages:

On ubuntu-22.04:
```
Error: Unsupported target! (platform='linux', version='18')
    at getSpecificVersionAndUrl (/home/runner/work/_actions/KyleMayes/install-llvm-action/v1.9.0/dist/index.js:343:47)
    at install (/home/runner/work/_actions/KyleMayes/install-llvm-action/v1.9.0/dist/index.js:360:36)
    at run (/home/runner/work/_actions/KyleMayes/install-llvm-action/v1.9.0/dist/index.js:390:16)
    at main (/home/runner/work/_actions/KyleMayes/install-llvm-action/v1.9.0/dist/index.js:406:15)
    at Object.<anonymous> (/home/runner/work/_actions/KyleMayes/install-llvm-action/v1.9.0/dist/index.js:412:21)
    at parcelRequire (/home/runner/work/_actions/KyleMayes/install-llvm-action/v1.9.0/dist/index.js:47:12)
    at Object.<anonymous> (/home/runner/work/_actions/KyleMayes/install-llvm-action/v1.9.0/dist/index.js:7994:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
Error: Unsupported target! (platform='linux', version='18')
```

On windows-2022:
```
Error: Unsupported target! (platform='win32', version='18')
    at getSpecificVersionAndUrl (D:\a\_actions\KyleMayes\install-llvm-action\v1.9.0\dist\index.js:343:47)
    at install (D:\a\_actions\KyleMayes\install-llvm-action\v1.9.0\dist\index.js:360:36)
    at run (D:\a\_actions\KyleMayes\install-llvm-action\v1.9.0\dist\index.js:390:16)
    at main (D:\a\_actions\KyleMayes\install-llvm-action\v1.9.0\dist\index.js:406:15)
    at Object.<anonymous> (D:\a\_actions\KyleMayes\install-llvm-action\v1.9.0\dist\index.js:412:21)
    at parcelRequire (D:\a\_actions\KyleMayes\install-llvm-action\v1.9.0\dist\index.js:47:12)
    at Object.<anonymous> (D:\a\_actions\KyleMayes\install-llvm-action\v1.9.0\dist\index.js:7994:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
Error: Unsupported target! (platform='win32', version='18')
```

Clang 17 works fine. [I think](https://github.com/KyleMayes/install-llvm-action/blob/be40c5af3a4adc3e4a03199995ab73aa37536712/index.ts#L71) version 18 is simply not yet supported?

**Comment by KyleMayes** [comment]
I've added [`v2.0.0`](https://github.com/KyleMayes/install-llvm-action/blob/master/CHANGELOG.md#200---2024-03-31) which reworks how download URLs are determined (now a script populates a JSON file by querying the GitHub API for the LLVM releases). This script has provided versions for the LLVM and Clang 18 and should make it much easier to add support for future LLVM and Clang versions.

Most users shouldn't need to change anything to move from `v1` to `v2`, see the above the link for what changed.
