### ISSUE TITLE
Specific LLVM versions fail

### ISSUE THREAD

**Issue by gentoo-root** [KyleMayes/install-llvm-action#67]
When I specified `version: "17.0.6"`, the action failed:

```
 Checking known assets (os=linux, arch=x64, version=17.0.6)...
Error: Unsupported version for platform (os=linux, arch=x64, version=17.0.6)!
    at $73b874f14e970995$export$da446a5ee2572b7 (/home/runner/work/_actions/KyleMayes/install-llvm-action/bb56a8457a77b95a5fa576c23731cbb162fd2056/dist/main.js:7615:41)
    at $73b874f14e970995$var$install (/home/runner/work/_actions/KyleMayes/install-llvm-action/bb56a8457a77b95a5fa576c23731cbb162fd2056/dist/main.js:7633:60)
    at $73b874f14e970995$export$889ea624f2cb2c57 (/home/runner/work/_actions/KyleMayes/install-llvm-action/bb56a8457a77b95a5fa576c23731cbb162fd2056/dist/main.js:7663:16)
    at $933db609b41224a7$var$main (/home/runner/work/_actions/KyleMayes/install-llvm-action/bb56a8457a77b95a5fa576c23731cbb162fd2056/dist/main.js:7681:61)
Error: Unsupported version for platform (os=linux, arch=x64, version=17.0.6)!
    at Object.<anonymous> (/home/runner/work/_actions/KyleMayes/install-llvm-action/bb56a8457a77b95a5fa576c23731cbb162fd2056/dist/main.js:7688:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
```

...although the corresponding [entry](https://github.com/KyleMayes/install-llvm-action/blob/bb56a8457a77b95a5fa576c23731cbb162fd2056/assets.json#L46) exists in assets.json. The [README](https://github.com/KyleMayes/install-llvm-action/blob/13bb038c217a6c7e33837aca5e5e0ce05dfd36d6/README.md?plain=1#L47) says it should be supported, however, from the code it looks like it always [appends a dot](https://github.com/KyleMayes/install-llvm-action/blob/bb56a8457a77b95a5fa576c23731cbb162fd2056/index.ts#L45) to the version number, so no matches can be found. Looks like it was broken with this recent [commit](https://github.com/KyleMayes/install-llvm-action/commit/0871d332bcc6ff656ebd529982c81b5b80b5feef#diff-dcdc3e0b3362edb8fec2a51d3fa51f8fb8af8f70247e06d9887fa934834c9122L100).

**Comment by KyleMayes** [comment]
Thanks for the contribution!
I've released `v2.0.1` and pointed `v2` at that version.
