### ISSUE TITLE
Is Windows the only github runner for LLVM 18?

### ISSUE THREAD

**Issue by Pat-Lafon** [KyleMayes/install-llvm-action#70]
Hello,

I am interested in updating my project to LLVM 18 now that brew added llvm 18. It seems like the standard runners I would reach for (ubuntu-latest or macos-latest) don't work while using `KyleMayes/install-llvm-action@v2.0.2`(which I needed to properly detect that macos-latest was arm instead of x86).

Looking at the https://github.com/KyleMayes/install-llvm-action/blob/master/assets.json, is the only option windows?

Feel free to close if not actionable.

```
0s
Run KyleMayes/install-llvm-action@v2.0.2
  with:
    version: 18
  env:
    LLVM_VERSION: 18
    RUSTDOCFLAGS: -D warnings
    RUSTFLAGS: -D warnings
    CARGO_INCREMENTAL: 0
    CARGO_TERM_COLOR: always
NodeJS process info = {"os":"darwin","arch":"arm64"}
Error: Unsupported version for platform (os=darwin, arch=arm64, version=18)!
Checking known assets (os=darwin, arch=arm64, version=18)...
    at $73b874f14e970995$export$da446a5ee2572b7 (/Users/runner/work/_actions/KyleMayes/install-llvm-action/v2.0.2/dist/main.js:7630:41)
Error: Unsupported version for platform (os=darwin, arch=arm64, version=18)!
    at $73b874f14e970995$var$install (/Users/runner/work/_actions/KyleMayes/install-llvm-action/v2.0.2/dist/main.js:7648:60)
    at $73b874f14e970995$export$889ea624f2cb2c57 (/Users/runner/work/_actions/KyleMayes/install-llvm-action/v2.0.2/dist/main.js:7679:16)
    at $933db609b41224a7$var$main (/Users/runner/work/_actions/KyleMayes/install-llvm-action/v2.0.2/dist/main.js:7701:61)
    at Object.<anonymous> (/Users/runner/work/_actions/KyleMayes/install-llvm-action/v2.0.2/dist/main.js:7707:1)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
```

**Comment by KyleMayes** [comment]
It looks like there haven't been arm64 macOS binaries (or x86-64 Linux binaries) added for any of the 18.x releases.  
(and they stopped adding x86-64 macOS binaries a while ago)

Unless a future release includes these or they are backfilled (which happens sometimes), then yes, Windows is the only default runner that will work for LLVM/Clang 18.x.
